name: test_flutter
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.2
  shared_preferences: ^2.2.2
  mobx: ^2.2.3
  build_runner: ^2.4.7
  flutter_mobx: ^2.2.0+1
  mobx_codegen: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
